@extends('layouts.admin')
@section('title','Sales')
@section('content_header')<div class="d-flex justify-content-between align-items-center"><h1>Sales</h1><a href="{{ route('sales.create') }}" class="btn btn-primary"><i class="bi bi-plus-circle mr-1"></i> New Sale</a></div>@stop
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="card"><div class="card-header"><form method="GET" action="{{ route('sales.index') }}"><div class="row"><div class="col-md-4 mb-2"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Invoice, customer, code or phone"></div><div class="col-md-3 mb-2"><input class="form-control" type="date" name="from_date" value="{{ request('from_date') }}"></div><div class="col-md-3 mb-2"><input class="form-control" type="date" name="to_date" value="{{ request('to_date') }}"></div><div class="col-md-2 mb-2"><button class="btn btn-secondary btn-block"><i class="bi bi-search"></i> Search</button></div></div></form></div>
<div class="card-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Total</th><th>Paid</th><th>Due</th><th>Status</th><th>Created By</th><th>Actions</th></tr></thead><tbody>
@forelse($sales as $sale)<tr><td>{{ $sale->invoice_no }}</td><td>{{ $sale->sale_date?->format('Y-m-d') }}</td><td>{{ $sale->customer->business_name ?? 'N/A' }}</td><td>{{ number_format((float)$sale->grand_total,2) }}</td><td>{{ number_format((float)$sale->paid_amount,2) }}</td><td>{{ number_format((float)$sale->due_amount,2) }}</td><td><span class="badge badge-{{ ['paid'=>'success','partial'=>'warning','pending'=>'danger'][$sale->payment_status ? strtolower($sale->payment_status) : ''] ?? 'secondary' }}">{{ ucfirst(strtolower($sale->payment_status ?? 'Pending')) }}</span></td><td>{{ $sale->user->name ?? 'N/A' }}</td><td><a class="btn btn-sm btn-info" href="{{ route('sales.show',$sale) }}">View</a> @can('admin')<a class="btn btn-sm btn-warning" href="{{ route('sales.edit',$sale) }}">Edit</a><form class="d-inline" method="POST" action="{{ route('sales.destroy',$sale) }}" onsubmit="return confirm('Delete this sale and restore its stock?')">@csrf @method('DELETE')<button class="btn btn-sm btn-danger">Delete</button></form>@endcan</td></tr>@empty<tr><td colspan="9" class="text-center">No sales found.</td></tr>@endforelse
</tbody></table></div>@if($sales->hasPages())<div class="card-footer">{{ $sales->links() }}</div>@endif</div>
@stop
