@extends('layouts.admin')
@section('title','Sale '.$sale->invoice_no)
@section('content_header')<div class="d-flex justify-content-between align-items-center"><h1>Sale {{ $sale->invoice_no }}</h1><div>@can('admin')<a class="btn btn-warning" href="{{ route('sales.edit',$sale) }}">Edit</a>@endcan <button class="btn btn-secondary" onclick="window.print()">Print</button> <a class="btn btn-secondary" href="{{ route('sales.index') }}">Back</a></div></div>@stop
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card" id="printArea"><div class="card-header"><strong>Invoice: {{ $sale->invoice_no }}</strong></div><div class="card-body"><div class="row mb-3"><div class="col-md-4"><strong>Customer</strong><br>{{ $sale->customer->business_name ?? 'N/A' }}<br>{{ $sale->customer->phone ?? '' }}</div><div class="col-md-4"><strong>Date</strong><br>{{ $sale->sale_date?->format('Y-m-d') }}</div><div class="col-md-4"><strong>Created By</strong><br>{{ $sale->user->name ?? 'N/A' }}</div></div>
<div class="table-responsive"><table class="table table-bordered"><thead><tr><th>#</th><th>Medicine</th><th>Batch</th><th>Qty</th><th>Unit Price</th><th>Discount</th><th>Total</th></tr></thead><tbody>@foreach($sale->items as $i=>$item)<tr><td>{{ $i+1 }}</td><td>{{ $item->medicine->name ?? 'N/A' }}</td><td>{{ $item->batch->batch_no ?? 'N/A' }}</td><td>{{ $item->quantity }}</td><td>{{ number_format((float)$item->unit_price,2) }}</td><td>{{ number_format((float)$item->discount,2) }}</td><td>{{ number_format((float)$item->total,2) }}</td></tr>@endforeach</tbody></table></div>
<div class="row justify-content-end"><div class="col-md-4"><table class="table table-sm"><tr><th>Subtotal</th><td>{{ number_format((float)$sale->subtotal,2) }}</td></tr><tr><th>Total Discount</th><td>{{ number_format((float)$sale->discount,2) }}</td></tr><tr><th>Invoice Discount</th><td>{{ number_format((float)$sale->invoice_discount,2) }}%</td></tr><tr><th>Grand Total</th><td><strong>{{ number_format((float)$sale->grand_total,2) }}</strong></td></tr><tr><th>Paid</th><td>{{ number_format((float)$sale->paid_amount,2) }}</td></tr><tr><th>Due</th><td>{{ number_format((float)$sale->due_amount,2) }}</td></tr><tr><th>Status</th><td>{{ ucfirst(strtolower($sale->payment_status ?? 'Pending')) }}</td></tr></table></div></div></div></div>
@stop
@push('css')<style>@media print{body *{visibility:hidden}#printArea,#printArea *{visibility:visible}#printArea{position:absolute;left:0;top:0;width:100%}}</style>@endpush
